name: Snowflake_CICD

#Controls when the action will run.
on:
  push:
    branch:
      - main, master
    paths:
      - 'dbscripts/**'

   # Allows you to run this workflow manually from the Action tab
   workflow_dispatch:


jobs:
  snowflake-cicd:
     runs-on: ubuntu-latest


     steps:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - name: checkout repository
         uses: actions/checkout@v2

       - name: use Python 3.12.x
         uses: actions/checkout@v2.2.1
         with:
            python-version: 3.12.x

       - name: Rubn schemachange
         env:
            SF_ACCOUNT: ${{ secret.SF_ACCOUNT }}
            SF_USERNAME: ${{ secrets.SF_USERNAME }}
            SF_ROLE: ${{ secrets.SF_ROLE }}
            SF_WAREHOUSE: ${{ secrets.SF_WAREHOUSE }}
            SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
         run:  |
            echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
            python --version
            echo "Step 1: Installing schemachange"
            pip install schemachange

            echo "Step 2: Running schemachange"
            schemachange -f $GITHUB_WORKSPACE/dbscripts -a $SF_ACCOUNT -u sekaba -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY  --create-change-history-table
         
